import type { Cliente, Auto, Reserva } from "./types"

// Datos mock que simulan la respuesta del backend Spring Boot
export const mockClientes: Cliente[] = [
  {
    id: 1,
    nombre: "Juan",
    apellido: "Pérez",
    email: "juan.perez@email.com",
    telefono: "+34 600 123 456",
    direccion: "Calle Mayor 123, Madrid",
    dni: "12345678A",
    fechaRegistro: "2024-01-15",
    activo: true,
  },
  {
    id: 2,
    nombre: "María",
    apellido: "García",
    email: "maria.garcia@email.com",
    telefono: "+34 600 234 567",
    direccion: "Avenida Principal 45, Barcelona",
    dni: "23456789B",
    fechaRegistro: "2024-02-20",
    activo: true,
  },
  {
    id: 3,
    nombre: "Carlos",
    apellido: "López",
    email: "carlos.lopez@email.com",
    telefono: "+34 600 345 678",
    direccion: "Plaza España 7, Valencia",
    dni: "34567890C",
    fechaRegistro: "2024-03-10",
    activo: true,
  },
]

export const mockAutos: Auto[] = [
  {
    id: 1,
    marca: "Toyota",
    modelo: "Corolla",
    anio: 2023,
    precio: 25000,
    kilometraje: 5000,
    combustible: "Híbrido",
    transmision: "Automática",
    color: "Blanco",
    descripcion: "Sedán híbrido con excelente eficiencia de combustible y tecnología avanzada.",
    imagenUrl: "/toyota-corolla-blanco-2023.jpg",
    disponible: true,
    caracteristicas: ["Sistema híbrido", "Cámara trasera", "Control crucero adaptativo", "Apple CarPlay"],
  },
  {
    id: 2,
    marca: "BMW",
    modelo: "Serie 3",
    anio: 2024,
    precio: 45000,
    kilometraje: 1000,
    combustible: "Gasolina",
    transmision: "Automática",
    color: "Negro",
    descripcion: "Sedán deportivo de lujo con alto rendimiento y tecnología de punta.",
    imagenUrl: "/bmw-serie-3-negro-2024.jpg",
    disponible: true,
    caracteristicas: ["Asientos de cuero", "Sistema de navegación", "Techo solar", "Bluetooth"],
  },
  {
    id: 3,
    marca: "Tesla",
    modelo: "Model 3",
    anio: 2024,
    precio: 50000,
    kilometraje: 500,
    combustible: "Eléctrico",
    transmision: "Automática",
    color: "Azul",
    descripcion: "Sedán eléctrico con autopilot, cero emisiones y tecnología innovadora.",
    imagenUrl: "/tesla-model-3-azul-2024.jpg",
    disponible: true,
    caracteristicas: ["Autopilot", "Carga rápida", 'Pantalla táctil 15"', "Premium audio"],
  },
  {
    id: 4,
    marca: "Honda",
    modelo: "CR-V",
    anio: 2023,
    precio: 32000,
    kilometraje: 8000,
    combustible: "Gasolina",
    transmision: "Automática",
    color: "Gris",
    descripcion: "SUV espacioso y confiable, ideal para familias.",
    imagenUrl: "/honda-crv-gris-2023.jpg",
    disponible: true,
    caracteristicas: ["Tracción 4x4", "Sistema de seguridad Honda Sensing", "Amplio maletero", "Bajo consumo"],
  },
  {
    id: 5,
    marca: "Audi",
    modelo: "A4",
    anio: 2023,
    precio: 42000,
    kilometraje: 3000,
    combustible: "Diesel",
    transmision: "Automática",
    color: "Plateado",
    descripcion: "Sedán premium con diseño elegante y alto confort.",
    imagenUrl: "/audi-a4-plateado-2023.jpg",
    disponible: false,
    caracteristicas: ["Interior premium", "Sistema multimedia MMI", "Faros LED", "Asientos calefactables"],
  },
  {
    id: 6,
    marca: "Ford",
    modelo: "Mustang",
    anio: 2024,
    precio: 55000,
    kilometraje: 200,
    combustible: "Gasolina",
    transmision: "Manual",
    color: "Rojo",
    descripcion: "Deportivo icónico con motor V8 y diseño agresivo.",
    imagenUrl: "/ford-mustang-rojo-2024.jpg",
    disponible: true,
    caracteristicas: ["Motor V8", "Suspensión deportiva", "Sistema de escape deportivo", "Modo Track"],
  },
]

export const mockReservas: Reserva[] = [
  {
    id: 1,
    clienteId: 1,
    autoId: 1,
    fechaReserva: "2024-03-01",
    fechaInicio: "2024-03-15",
    fechaFin: "2024-03-20",
    estado: "Confirmada",
    comentarios: "Necesito el auto para un viaje familiar.",
    montoTotal: 25000,
  },
  {
    id: 2,
    clienteId: 2,
    autoId: 3,
    fechaReserva: "2024-03-05",
    fechaInicio: "2024-03-25",
    fechaFin: "2024-03-30",
    estado: "Pendiente",
    comentarios: "Interesado en probar el modelo eléctrico.",
    montoTotal: 50000,
  },
  {
    id: 3,
    clienteId: 3,
    autoId: 5,
    fechaReserva: "2024-02-28",
    fechaInicio: "2024-03-10",
    fechaFin: "2024-03-12",
    estado: "Completada",
    comentarios: "Excelente servicio.",
    montoTotal: 42000,
  },
]
